services:
  - type: web
    name: be-frontend-banco
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm run serve"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://be-backend-hfib.onrender.com"
      - key: PORT
        value: "3000"

  - type: web
    name: be-backend-hfib
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: RAPYD_ACCESS_KEY
        value: "rak_41EE71BF4EF85F075A6B"
      - key: RAPYD_SECRET_KEY
        value: "rsk_3fc4dc1ddfc628b218e7a913f83cf75268ece438ea7aabea9bddcd3c25951800612763fec5c7a219"
      - key: RAPYD_BASE_URL
        value: "https://sandboxapi.rapyd.net"
      - key: FRONTEND_URL
        value: "https://www.bancoexclusivo.lat"
      - key: DATABASE_URL
        value: "sqlite:banco.db"
      - key: CORS_ORIGIN
        value: "https://www.bancoexclusivo.lat"
